contact/urls.py
from contact import views
from django.urls import path

app_name = "contact"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),

    # contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name="contact"),
    path('contact/<int:contact_id>/update/', views.update, name="update"),
    path('contact/<int:contact_id>/delete/', views.delete, name="delete"),
    path('contact/create/', views.create, name="create"),


    # user
    path('user/create/', views.register, name="register"),
    path('user/login/', views.login_view, name="login"),
    path('user/logout/', views.logout_view, name="logout"),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('', include("contact.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(("Categoria"), max_length=50)
   
    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    first_name = models.CharField(("Nome"), max_length=50, help_text='help text')
    last_name = models.CharField(("Sobrenome"), max_length=50, blank=True)
    phone = models.CharField(("Telefone"), max_length=50)
    email = models.EmailField(("Email"), max_length=254, blank=True)
    created_date= models.DateTimeField(("Data Registro"),default=timezone.now)
    description = models.TextField(("Comentarios"),blank=True)
    show=models.BooleanField(default=True)
    picture = models.ImageField(("Foto"),blank=True,upload_to='pictures/%Y/%m/%d')
    category = models.ForeignKey(Category,verbose_name= ("Categoria"), 
                                 on_delete=models.SET_NULL, blank=True,null=True)
    owner = models.ForeignKey(User,verbose_name= ("Usuario"), 
                                 on_delete=models.SET_NULL, blank=True,null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from contact.models import Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import models


class ContactForm(forms.ModelForm):

    # criando um campo fora do model

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ), required=False
    )

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    class Meta:
        model = Contact
        fields = (
            'category', 'first_name', 'last_name',
            'phone', 'email', 'description', 'picture',
        )
        widgets = {
            # 'first_name': forms.PasswordInput()
            # 'category': forms.TextInput(
            #     attrs={'placeholder':'Category', }
            # ),
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Nome', },
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Sobrenome', }
            ),
            'email': forms.EmailInput(
                attrs={'placeholder': 'Email', },
            ),
            'phone': forms.TextInput(
                attrs={'placeholder': 'Telefone', }
            )

        }

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid')

            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()

    def clean_first_name(self):

        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':

            self.add_error(
                'first_name',
                ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )

        return first_name


class RegisterForm(UserCreationForm):

    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email

contact/views/contact_forms.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            messages.success(request, 'Conatato gravado com sucesso...')
            return redirect('contact:update', contact_id=contact.pk)
        messages.error(request, 'Formulario nao gravado, verifique erros...')
        return render(
            request,
            'contact/create.html',
            context)

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context)


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            messages.success(request, 'Contato atualizado com sucesso...')
            return redirect('contact:update', contact_id=contact.pk)
        messages.error(request, 'Formulario nao gravado, verifique erros...')
        return render(
            request,
            'contact/create.html',
            context)

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context)


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user)

    confirmation = request.POST.get('confirmation', 'no')
    print(confirmation)

    if confirmation == 'yes':
        contact.delete()  # deleta direto
        return redirect('contact:index')

    return render(request,
                  'contact/contact.html',
                  {'contact': contact,
                      'confirmation': confirmation})

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        )\
        .order_by("-id")
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - '
    }
    return render(
        request,
        'contact/index.html',
        context)


def index(request):
    contacts = Contact.objects\
        .order_by("-id")\
        .filter(show=True)
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }
    return render(
        request,
        'contact/index.html',
        context)


def contact(request, contact_id):
    # single_contact = Contact.objects.get(pk=contact_id)
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    context = {
        'contact': single_contact,
        'site_title': f'{single_contact.first_name} {single_contact.last_name} - '
    }
    return render(
        request,
        'contact/contact.html',
        context)

contact/views/contatc_views.py
from django.shortcuts import render,get_object_or_404,redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)           
        )\
        .order_by("-id")
    paginator = Paginator(contacts, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
        
    context = {
        'page_obj':page_obj,
        'site_title':'Search - '
    }
    return render(
        request,
        'contact/index.html',
        context)

def index(request):
    contacts = Contact.objects\
        .order_by("-id")\
        .filter(show=True)
    paginator = Paginator(contacts, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    

    context = {
        'page_obj':page_obj,
        'site_title':'Contatos - '
    }
    return render(
        request,
        'contact/index.html',
        context)


def contact(request,contact_id):
    # single_contact = Contact.objects.get(pk=contact_id)
    single_contact = get_object_or_404(Contact,pk=contact_id,show=True)
    
    context = {
        'contact':single_contact,
        'site_title': f'{single_contact.first_name} {single_contact.last_name} - '
    }
    return render(
        request,
        'contact/contact.html',
        context)

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario gravado sucesso...')
            return redirect('contact:login')

        messages.error(request, 'Formulario nao gravado, contem  erro...')
    return render(
        request,
        'contact/register.html',
        {'form': form}
    )


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            messages.success(request, f'{user}, Logado com sucesso')
            auth.login(request, user)
            return redirect('contact:index')
        messages.error(request, 'Erro de login')

    return render(
        request,
        'contact/login.html',
        {'form': form}
    )


@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{contact.first_name}} {{contact.last_name}}
    </h1>
    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>   

    {% if user == contact.owner %}
        <div class="contact-links">
            <a class="btn btn-link" href= "{% url "contact:update" contact.id %}"> UPDATE</a>
            <form action= {% url "contact:delete" contact.id %} method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes">
                <button class= "btn btn-link btn-delete" type="submit"> CONFIRMA? </button>
                {% else %}
                <button class= "btn btn-link btn-delete" type="submit"> DELETE </button>
                {% endif %}
            </form>
        </div>
    {% else %}
        <p><b>Owner:</b> {{contact.owner}} </p>       
    {% endif %}

    
    {% if contact.picture %}
        <p>
            <img src=" {{contact.picture.url}}" alt=" {{conatact.first_name}}  {{contatct.last_name}}">
        </p>   
    {% endif %}
</div>

{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>CREATE A CONTACT</h2>

  <form 
    action="{{ form_action}}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    
 
 
    <div class="form-content">
    {% for field in form  %}
        <div class="form-group">
           <label for="{{field.id_for_label}}">{{field.label}}</label>
           {{field}}
           {{field.erros}}
           {% for error in form.errors %}
                {{error}}
            {% endfor %}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}

            {% if field.name == 'picture' and field.value.url %}
              <img src="{{field.value.url}}" alt="">
            {% endif %}
        </div>
    {% endfor %}
        </div>
       

        {% if form.non_field_errors %}
          <div class="form-content">
            <div class="form-group">
             <div class="message error">
                {{ form.non_field_errors }}
             </div>
            </div>
          </div>
        {% endif %}

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>   
{% endblock content%}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %} 
{% if page_obj %}
    <div class="responsive-table">
        <table class ="contacts-table">
            <caption class="table-caption ">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header"> ID</th>
                    <th class="table-header"> Nome</th>
                    <th class="table-header"> Sobrenome</th>
                    <th class="table-header"> Contatos</th>
                    <th class="table-header"> email</th>
                </tr>   
            </thead>
            <tbody>
              {% for contact in page_obj %}
                <tr class="table-row">
                    <td class="table-cel">
                      <a class="table-link" 
                      href="{% url "contact:contact" contact.id %}">
                      {{contact.id}}
                    </a>  
                </td>
                <td class="table-cel">
                    <a class="table-link" 
                     href="{% url "contact:contact" contact.id %}">
                            {{contact.first_name}}
                          </a>  
                    </td>
                    <td class="table-cel">
                        <a class="table-link" 
                        href="{% url "contact:contact" contact.id %}">
                        {{contact.last_name}}
                          </a>  
                    </td>
                    <td class="table-cel">
                        <a class="table-link" 
                        href="{% url "contact:contact" contact.id %}">
                        {{contact.phone}}
                          </a>  
                    </td>
                    <td class="table-cel">
                        <a class="table-link" 
                        href="{% url "contact:contact" contact.id %}">
                        {{contact.email}}
                          </a>  
                    </td>

                </tr>
                {% endfor %}  
            </tbody>    
        </table>    
    </div>
{% else  %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado
        </h1>
    
    </div>   
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>Login</h2>
    {% if user.is_authenticated %}
        <p>
            Voce fez login como {{user}}. 
            Clique <a href="{% url 'contact:logout' %}"> aqui</a> 
            para sair
        </p>
    {% else %}
         {% include "contact/partials/_user-form.html" %}
    {% endif %} 

</div>   
{% endblock content%}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>Register a User</h2>

    {% include "contact/partials/_user-form.html" %}
</div>   
{% endblock content%}